[profile.default]
src = "src"
out = "out"
libs = ["lib", "../1a/lib"]
evm_version = "paris"   # PUSH0 비활성화
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
coston2 = "${RPC_URL}"
